/* Lista productos como un array, con imagenes de 800pxx800px*/

const products = [
{
    id: 1,
    productName:  "nRF24L01 + PA + LNA",
    price: 16000,
    quantity: 1,
    img: "./images/nRF24L01PALNA.jpg",
    description: "Este módulo usa un nuevo transceptor de la compañía Nordic Semiconductor, el nRF24L01+.Este transceptor opera en la banda de 2.4GHz y tiene muchas características nuevas. Incluye circuitería tanto de PA (preamplificador) como de LNA (Low-noise amplifier), con la antena externa puede alcanzar distancias más grandes que las versiones normales. Es similar al nRF2401+ e incorpora adicionalmente extra pipelines, buffers, y un modo de auto retransmisión. Viene con la antena para 2.4GHz (2dB) con una tasa de trasmisión de hasta 250kbps al aire libre y puede alcanzar una distancia de hasta 1 kilómetro. El módulo utiliza 8 pines para su interfaz externa y funciona con el estándar de comunicación SPI.",
    specifications: "Voltaje de alimentación: 3-3.6V (3.3V recomendado), Potencia máxima de salida: +20 dBm, Corriente (máxima) en modo de emisión: 115 mA, Corriente (máxima) en modo de recepción: 45 mA, Modo de apagado-espera: 4.2uA, Sensibilidad a 2 Mbps en modo de recepción: -92dBm, Sensibilidad a 1 Mbps en modo de recepción: -95 dBm, Sensibilidad a 250 kbps en modo de recepción: -104dBm, Ganancia PA : 20dB, Ganancia LNA: 10dB, Figura de ruido LNA: 2.6 dB, Ganancia de la Antena (pico): 2 dBi, Distancia a Tasa de 2MB (zona abierta): 520m, Distancia a Tasa de 1MB (zona abierta): 750m, Distancia a Tasa de 250Kb (zona abierta): 1000m",
},
{
    id: 2,
    productName:  "nRF24L01 Module",
    price: 11000,
    quantity: 1,
    img: "./images/nRF24L01.jpg",
    description: "Este módulo usa un nuevo transceptor de la compañía Nordic Semiconductor, el nRF24L01+.Este transceptor opera en la banda de 2.4GHz y tiene muchas características nuevas. Es similar al nRF2401+ e incorpora adicionalmente extra pipelines, buffers, y un modo de auto retransmisión. El módulo utiliza 8 pines para su interfaz externa y funciona con el estándar de comunicación SPI. Pines nRF24L01+.",
    specifications: "Voltaje de alimentación de 1.9 a 3.6V, Banda ISM de 2.4GHz, Velocidad de datos de hasta 2Mbps.,Operación a muy baja potencia.,11.3mA TX a 0dBm de potencia de salida,12.3mA RX a una velocidad de datos de 2Mbps,900nA estando apagado,22μA en espera-I,ShockBurst™ Mejorado,Compatible con nRF2401A, 02, E1 y E2,Distancia de alcance de hasta 40 mts en línea de vista",  
},
{
    id: 3,
    productName:  "nRF24L01 Adapter",
    price: 5000,
    quantity: 1,
    img: "./images/nRF24L01Adapter.jpg",
    description:"Este módulo hace que sea fácil de usar transceptores de tipo NRF24L01 en 5 voltios como sistemas Arduino.Regula los 5 voltios a 3,3 V y proporciona capacitores de paso para un funcionamiento fiable. 5V DC se requiere para alimentar este módulo.",
    specifications: "NRF24L01 transceptores se conectan a este pequeño módulo, Funciona con baja o media potencia (con amplificador de potencia) transceptores NRF24L01, Fácil de conectar a las señales NRF24L01, regulador de 3.3V proporciona corriente adecuada para funcionar nRF24L01, capacitores de paso mejorar la estabilidad transceptor",
},
{
    id: 4,
    productName:  "AMS1117 3.3v Module",
    price: 2500,
    quantity: 1,
    img: "./images/ams11173.3v.jpg",
    description:"Módulo de suministro de energía de 3.3V, puesto que la mayoría de los circuitos digitales funcionan a base de 4.8V a 5V. Posee una interfaz compatible con una board de expansión para un regulador de potencia.",
    specifications: "Voltaje de entrada: 4.7V a 7V, Voltaje de salida: 3.3V, Corriente de salida: 800mA, Indicador de potencia: LED rojo, Temperatura de operación: -40°C a +150°C, Diseño especial de 2 pines., Fijación directamente en una board externa.",
},
{
    id: 5,
    productName:  "ESP32 Wrover Cam SD 1Gb",
    price: 189000,
    quantity: 1,
    img: "./images/esp32wrover.jpg",
    description: "La placa Freenove ESP32-Wrover CAM es una placa de desarrollo ESP32 con el chip ESP32-Wrover-E (con 4 MB de PSRAM) y una cámara OV2640. Tiene un convertidor de USB a UART, por lo que es sencillo cargar el código en la placa. Solo necesitaconectar un cable USB a la placa y conectarlo a su computadora para cargar el código o aplicar energía. No se necesitan circuitos adicionales ni un programador FTDI (a diferencia de la placa ESP32-CAM AI-Thinker). Esta placa cuenta con una cámara OV2640, varios GPIO para conectar periféricos y un programador integrado con un conector USB, lo que facilita la carga de código en la placa. Echaremos un vistazo rápido a la placa y le mostraremos algunos ejemplos de cómo programarla usando el núcleo Arduino para el ESP32.",
    specifications: "Chip ESP32-Wrover-E con PSRAM de 4 MB, USB a UART integrado (controladores CH340C): no es necesario un programador FTDI, Cámara OV2640 2 Megapíxeles, Botones BOOT y RST, Indicadores LED (RX/TX ON/OFF y LED integrado (GPIO2)), Antena a bordo.",
},
{
    id: 6,
    productName:  "ATMega 328p Chip",
    price: 21000,
    quantity: 1,
    img: "./images/atmega328p.jpg",
    description:"Microcontrolador ATMEGA328P fabricado por Atmel (Microchip). Pertenece a la familia AVR con arquitectura RISC de 8 bits. Cuenta con poderosas instrucciones que se ejecutan en su mayoría en un solo ciclo de reloj, por lo que puede alcanzar un desempeño cercano a 1 MIPS por cada 1 Mhz en la frecuencia de reloj.",
    specifications: "Fabricante: Atmel (Microchip)., Voltaje de operación: 1.8 a 5.5 VDC, Arquitectura de CPU: 8 bit AVR., Memoria flash: 32 KB., Memoria RAM: 2 KB., EEPROM: 2 KB., Frecuencia de operación: 20 Mhz., Pines de IO: 23.",
},
{
    id: 7,
    productName:  "ADXL345 Acelerometro 3x",
    price: 10000,
    quantity: 1,
    img: "./images/adxl346.jpg",
    description:"Este módulo basado en un acelerómetro ADXL345 de 3 ejes pose una sensibilidad ajustable por software con rangos de operación de +/- 2g, 4g, 8g y 16g Se puede comunicar por SPI o por I2C esto hace que sea un módulo adaptable a muchas placas basadas en PIC, Arduino u otras plataformas.Este módulo es muy utilizado en proyectos de robótica, para detectar impactos, vibraciones, para analizar movimiento e inclinaciones en vehículos inteligentes o para implementar mandos como el del Nintendo wii.",
    specifications: "Voltaje de operación: 3V - 5V, Consumo de corriente: 23 µA en medición y 0.1 µA en standby, Alta sensibilidad, Rango Acelerómetro: +/- 2g, 4g, 8g y 16g, Resolución de hasta 13 bits a ± 16 g (manteniendo 4 mg / LSB), Grados de libertad: 3 ejes, Regulador de voltaje integrado",
},
{
    id: 8,
    productName:  "CAM Ov7670",
    price: 21000,
    quantity: 1,
    img: "./images/camov7670.jpg",
    description:"Este módulo está basado en un sensor de imagen de Omnivision OV760 (resolución de 8 Bits) que mejora la calidad de imagen mediante la reducción o la eliminación de la óptica de electrónica o defecto, tales como fijo patrón de ruido, la cola- floreciente, claro y de color estable de la imagen, además del polvo flotante. Cuenta con una cámara VGA, siendo la más económica que se puede encontrar en el mercado. Se puede usar para proyectos en donde se requiera una buena resolución de la imagen (de manera económica). Las imágenes son capturadas a través del sensor OV760 almacenándose en la memoria FIFO, dando el tiempo necesario a la CPU externa, lo cual permite una disponibilidad a través de un bus SCCB (que prácticamente es un I2C-RawRGB), RGB (GRB4:02:02, RGB565/555/444), YUV (4:2:2 ) y YCbCr (4:2:2), como las lí­neas del OV7670 que informan del barrido vertical (VSYNC) y horizontal (HREF).",
    specifications: "Voltaje de entrada 2.5V3V, Potencia de funcionamiento 60mW/15fps VGA YUV, Temperatura -30°C~+70°C, Lente 1/6, Ángulo visión 25°, Máx.Velocidad fotogramas 30fps VGA, Sensibilidad 1.3V/(lux- seg), Señal a ruido 46dB, Rango dinámico 52dB, Modo de navegación por fila, Resolución VGA 640x480 pixeles (30fps)",
},
{
    id: 9,
    productName:  "ATMega 328p Chip",
    price: 21000,
    quantity: 1,
    img: "./images/atmega328p.jpg",
    description:"Microcontrolador ATMega328P-PU precargado con el Bootloader de la tarjeta Arduino Uno R3. Puedes usar este chip con el entorno Arduino en tus proyectos, sin necesidad de utilizar una tarjeta Arduino Uno, lo puedes usar tambíen como un Arduino Uno standalone. También sirve como repuesto para el que trae la tarjeta Arduino Uno en caso de mal funcionamiento de este microcontrolador",
    specifications: "Voltaje de operación: 1.8 VDC5.5 VDC., Consumo máximo de corriente: 2.7 miliamperios., Encapsulado: DIP de 28 pines., Puertos PWM: 6., Puertos seriales USART: 1., Conversores ADC de 10 bits: 6., Puertos sincrónicos (SPI, I2C): 1.,Frecuencia Máxima de operación: 20 MHz., Memoria de Programa tipo Flash: 32 KBytes., Memoria SRAM: 2 KBytes., Memoria EEPROM: 1 KBytes., Número de Timers/contadores: 3.,Pines de entrada/salida digitales: 13 pines., Rango de temperatura de operación: -40ºC a +85ºC., Fabricante: Microchip.",
},
{
    id: 10,
    productName:  "HC-SR04",
    price: 5000,
    quantity: 1,
    img: "./images/hc-sr04.jpg",
    description:"El HC-SR04 es un sensor de distancias por ultrasonidos capaz de detectar objetos y calcular la distancia a la que se encuentra en un rango de 2 a 450 cm. El sensor funciona por ultrasonidos y contiene toda la electrónica encargada de hacer la medición. Su uso es tan sencillo como enviar el pulso de arranque y medir la anchura del pulso de retorno. De muy pequeño tamaño, el HC-SR04 se destaca por su bajo consumo, gran precisión y bajo precio por lo que esta reemplazando a los sensores polaroid en los robots mas recientes.",
    specifications: "Dimensiones del circuito: 43 x 20 x 17 mm, Tensión de alimentación: 5 Vcc, Frecuencia de trabajo: 40 KHz, Rango máximo: 4.5 m, Rango mínimo: 1.7 cm, Duración mínima del pulso de disparo (nivel TTL): 10 μS., Duración del pulso eco de salida (nivel TTL): 100-25000 μS., Tiempo mínimo de espera entre una medida y el inicio de otra 20 mS.",
},
{
    id: 11,
    productName:  "HTU21 Sensor",
    price: 21000,
    quantity: 1,
    img: "./images/htu21.jpg",
    description:"Sensor de Temperatura y humedad HTU21",
    specifications: "Voltaje de funcionamiento: 1.5V ~ 3.6V, Rango de humedad: 0 ~ 100%RH, Rango de exactitud de humedad: 10% RH ~ 95% RH, Histéresis de humedad:±1% RH, Rango de temperatura: - 40ºC ~ 105ºC, Tiempo de medición: 50ms, Tiempo de respuesta: 5s, Interface: I2C, Consumo máximo de potencia: 2.7 uW, Temperatura de operación: - 40ºC ~ 105ºC, Temperatura de almacenamiento: - 40ºC ~ 125ºC",
},
{
    id: 12,
    productName:  "NIVEL AGUA Sensor",
    price: 6000,
    quantity: 1,
    img: "./images/sensor_nivel_h2o.jpg",
    description:"El sensor de nivel de agua es muy fácil de usar. Las gotas de agua en el sensor se identifican por una serie de cables paralelos expuestos para medir el tamaño de las gotas de agua/cantidad con el fin de determinar el nivel del agua. Fácil de calcular la cantidad de agua con la salida del valor analógico. Un sencillo sensor de agua / gotas de lluvia, que produce una señal analógica proporcional a la humedad detectada, o al nivel de agua que recoja. Es un sensor de pequeñas dimensiones pensado para detectar el agua de lluvia o bien pequeñas modificaciones de nivel de agua (Un par de cm) para detectar filtraciones o fugas de líquido.",
    specifications: "Tipo de Sensor: Analógico, Área de detección: 40mmx16mm, Temperatura de funcionamiento: 10 C a 30 C, Humedad: 10 % - 90 % sin condensación, Dimensiones: 65 mm X 20 mm X 8 mm, Voltaje de operación: 3-5VDC, Corriente de operación: menos de 20mA",
},
];